[package]
name = "sesh"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.23" 
serde = { version = "1.0.219", features = ["derive"] }
walkdir = "2.5.0"
dirs = "6.0.0"
git2 = "0.20.2"
nucleo = "0.5.0"
ratatui = "0.29.0"
crossterm = "0.29.0"
color-eyre = "0.6.5"
tui-input = "0.12.1"
