[test-groups]
tmux = { max-threads = 1 }
integration = { max-threads = 1 }
script = { max-threads = 1}

[[profile.default.overrides]]
filter = "test(tmux::)"
test-group = "tmux"

[[profile.default.overrides]]
filter = "test(script::)"
test-group = "script"

[[profile.default.overrides]]
filter = "binary(session_manager)"
test-group = "integration"

[[profile.default.overrides]]
filter = "binary(repo_search)"
test-group = "integration"
