[test-groups]
tmux-relaiant = { max-threads = 1 }

[[profile.default.overrides]]
filter = "test(tmux::)"
test-group = "tmux-relaiant"

[[profile.default.overrides]]
filter = "test(script::)"
test-group = "tmux-relaiant"

[[profile.default.overrides]]
filter = "binary(session_manager)"
test-group = "tmux-relaiant"

[[profile.default.overrides]]
filter = "binary(repo_search)"
test-group = "tmux-relaiant"

[[profile.default.overrides]]
filter = "binary(config)"
test-group = "tmux-relaiant"
