name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y libluajit-5.1-dev tmux

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - name: Run tests
      run: |
        cargo nextest run --features="integration_test"
